export const AUTH_START = 'AUTH_START';
export const AUTH_END = 'AUTH_END';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const SET_USER = 'SET_USER';

export const CLEAN_UP = 'CLEAN_UP';

export const RECOVERY_START = 'RECOVERY_START';
export const RECOVERY_SUCCESS = 'RECOVERY_SUCCESS';
export const RECOVERY_FAIL = 'RECOVERY_FAIL';

export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const ADD_SEARCH_HISTORY = 'ADD_SEARCH_HISTORY';
export const REMOVE_SEARCH_HISTORY = 'REMOVE_SEARCH_HISTORY';
export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY';

export const SET_FRIENDS_START = 'SET_FRIENDS_START';
export const SET_FRIENDS = 'SET_FRIENDS';
export const SET_FRIENDS_END = 'SET_FRIENDS_START';

export const REQUEST_START = 'REQUEST_START';
export const REQUEST_SUCESS = 'REQUEST_SUCESS';

export const REQUEST_DECLINE_START = 'REQUEST_DECLINE_START';
export const REQUEST_DECLINE_SUCCESS = 'REQUEST_DECLINE_SUCCESS';

export const REQUEST_ACCEPT_START = 'REQUEST_ACCEPT_START';
export const REQUEST_ACCEPT_SUCCESS = 'REQUEST_ACCEPT_SUCCESS';

export const FETCH_PROFILE_URL = 'FETCH_PROFILE_URL';

export const FRIENDS_CLEAN_UP = 'FRIENDS_CLEAN_UP';

export const SET_CHAT = 'SET_CHAT';
